### PR TITLE
Allow to define cursor position after expansion

### PR DESCRIPTION
**Pull request by burneyy**
- With the keyword `__CURSOR__` one can specify the position of the cursor after expanding the abbreviation using space
  - e.g. `abbr ccr="conan create __CURSOR__ demo/testing"` places the cursor between `create` and `demo/testing` after the expansion (inspired by [stackoverflow](https://stackoverflow.com/questions/28573145/how-can-i-move-the-cursor-after-a-zsh-abbreviation))
  - can also be used to omit the trailing whitespace (e.g. `abbr trm="rm -rf /tmp/__CURSOR__`")

### CODE REVIEW

**Comment by olets** [comment]
Thanks for the contribution @burneyy!

My immediate zsh-abbr priority is getting v5 out. (Long-time listeners will know it's been in the works for a while. Work and afk life is also busy, so I'm reserving the right to get delayed 😃 However I'm actively working on a push to the finish line — in fact that's why I'm at my computer on this lovely weekend afternoon!) I'd be happy to talk more about this and to look at your implementation after I've cut that release.

> specify the position of the cursor after expanding the abbreviation

Neat idea! No promises yet —I want to take time to think about any possible drawbacks— but it seems useful and like a safer way of satisfying #21.

> `__CURSOR__`

Something specific to zsh-abbr would be safer. Theoretically possible that someone would be using `__CURSOR__` for something else. Maybe `ZSH_ABBR_EXPANSION_CURSOR`?

I think `abbr-expand-and-accept` should probably cut out the cursor keyword from the expansion. What do you think?

> omit the trailing whitespace

You can already do this by binding a key to `abbr-expand` ([docs link](https://github.com/olets/zsh-abbr#advanced:~:text=Default%20binding-,abbr%2Dexpand,-If%20following%20an); I know it's hard to find in the very long README. v5 will come with a better docs). I agree that in a sense it would be reasonable to disable `abbr-expand-and-space`'s space in the custom cursor location case, but I'd rather not blur the line between `abbr-expand` and `abbr-expand-and-space`.  My initial thought is it's okay to require custom-cursor-position powerusers to use a custom binding. Is it possible for both `abbr-expand` and `abbr-expand-and-space` to support the cursor position?

> Immediately trigger the syntax highlighting

So far my decision has been to not build in support for any specific syntax highlighters. It adds maintenance overhead / risk — if zsh-syntax-highlighting changes the name of their function, zsh-abbr will break.

Have you tried something like this?

```shell
widget-expand-abbreviation-and-highlight-line() {
  abbr-expand
  _zsh_highlight
}

zle -N expand-and-highlight

bindkey "mybindinggoeshere" widget-expand-abbreviation-and-highlight-line

# load zsh-abbr here
```

(Untested)

**Comment by olets** [comment]
(edited my comment — burneyy if you're already here and reading, reload)

**Comment by burneyy** [comment]
Hey @olets, thanks for the quick response!


> > `__CURSOR__`
> 
> Something specific to zsh-abbr would be safer. Theoretically possible that someone would be using `__CURSOR__` for something else. Maybe `ABBR_EXPANSION_CURSOR`?

I have considered that as well, however since googling for "__CURSOR__" didn't lead to any reasonable results, I thought it was safe and unique enough - but indeed something a bit more verbose might be safer.
I also considered introducing an option that needs to be set when adding an abbreviation with a custom cursor position like `abbr add -c myabbr="some command with a custom __CURSOR__ position"` but this would need to be saved somehow along with the abbreviations and is probably too much overhead, what do you think?

> I think `abbr-expand-and-accept` should probably cut out the cursor keyword from the expansion. What do you think?

Possibly, yeah... I personally do not have a use-case for abbreviations with a custom cursor position that would be useful also when executing immediately. I do stuff like `rm -rf <some_location>/__CURSOR__` where I actually prefer to keep the "__CURSOR__" string when I accidentally press enter such that not the whole `<some_location>` directory gets deleted. It is something to think about for sure.

> > omit the trailing whitespace
> 
> You can already do this by binding `abbr-expand` ([docs link](https://github.com/olets/zsh-abbr#bindings); I know it's hard to find in the very long README. v5 will come with a better docs).

True, but I would rather like to save this information along with the abbreviation and not having to think about it when expanding it.
 
> In a sense it would be reasonable to disable `abbr-expand-and-space`'s space in the custom cursor location case… but instead I would expect `abbr-expand-and-space` to still add space at the end of the entire expansion (not immediately before where the cursor keyword was).
> 
> I'd rather not blur the line between `abbr-expand` and `abbr-expand-and-space`. My initial thought is it's okay to require custom-cursor-position powerusers to use a custom binding.
> 
> Is it possible for both `abbr-expand` and `abbr-expand-and-space` to support the cursor position?

I kind of think of pressing space to just trigger the expansion and not actually inserting a literal space. So in fact, I would even rather have to specify a space within the definition of the abbreviation than by default appending one when pressing the space button. But I guess that is just me and probably highly debatable... ;)

> 
> > Immediately trigger the syntax highlighting
> 
> So far my decision has been to not build in support for any specific syntax highlighters. It adds maintenance overhead / risk.
> 
> Have you tried something like this? (in `.zshrc`)
> 
> ```shell
> expand-abbreviation-and-highlight-line() {
>   abbr-expand
>   _zsh_highlight
> }
> 
> zle -N expand-abbreviation-and-highlight-line
> 
> bindkey "mybindinggoeshere" expand-abbreviation-and-highlight-line
> 
> # load zsh-abbr here
> ```
> 
> (Untested)

Yes looks reasonable to do this externally, I will remove that part of the PR again I guess.

Have a nice remaining weekend!

**Comment by burneyy** [comment]
I have now removed the syntax highlighting part from the PR.

For anyone interested, you can put the following snippet into your `.zshrc` to enable it externally:
```
# Enable syntax highlighting after expanding with space
expand_abbreviation_and_space_and_highlight() {
  _abbr_widget_expand_and_space
  _zsh_highlight
}
zle -N expand_abbreviation_and_space_and_highlight
bindkey " " expand_abbreviation_and_space_and_highlight
```

**Comment by burneyy** [comment]
Following our discussion, I have tweaked the implementation now as follows:

1. The cursor position marker (default: `__ABBR_CURSOR__`) can be adjusted through the parameter `ABBR_CURSOR_MARKER`
2. The cursor position marker is now supported for all three types of expansions (expand, expand-and-accept, expand-and-space)
3. For expand-and-space, no additional space is inserted when a custom cursor position was specified

Caveats:
Typing in `__ABBR_CURSOR__` (outside of the usage of zsh-abbr) will cause the cursor to jump to that position. Maybe it is safer to disable that functionality by default? However, I think that string is specific enough to not be typed in another context (without being aware of it at least)

**Comment by olets** [comment]
>  the following snippet … `_abbr_widget_expand_and_space`

Glad this came up! `_abbr_widget_expand_and_space` is supposed to be deprecated. Use `abbr-expand-and-space` instead.  In v5 `_abbr_widget_expand_and_space` will be gone and `abbr-expand-and-space` will be your only option. I've cut a new version, v4.8.1, to add deprecation warnings.

> I would even rather have to specify a space within the definition of the abbreviation than by default appending one when pressing the space button

For anyone else who wants this: this is supported even without this PR's changes. Disable the default keybindings (`ABBR_DEFAULT_BINDINGS=0`) and then bind space to `abbr-expand`.

**Comment by burneyy** [comment]
> Glad this came up! `_abbr_widget_expand_and_space` is supposed to be deprecated. Use `abbr-expand-and-space` instead. In v5 `_abbr_widget_expand_and_space` will be gone and `abbr-expand-and-space` will be your only option. I've cut a new version, v4.8.1, to add deprecation warnings.
 Got it!

> For anyone else who wants this: this is supported even without this PR's changes. Disable the default keybindings (`ABBR_DEFAULT_BINDINGS=0`) and then bind space to `abbr-expand`.

But unfortunately then, one cannot use space as a „normal“ space anywhere else. I guess I could add a new function abbr-expand-or-space that does what I intended…

**Comment by burneyy** [comment]
Btw, there is a [big update incoming for abbreviations in fish](https://github.com/fish-shell/fish-shell/pull/9313) where one of the new features is support for a custom cursor position

**Comment by keremciu** [comment]
this is a great update! it will be very useful for my abbrs

**Comment by olets** [comment]
Quick note to say other things are keeping me busy but this is still on my mind and something I'd like to eventually support

**Comment by gforien** [comment]
Very useful feature indeed

**Comment by olets** [comment]
Thanks for your patience, all!

Replaced this with

- #111 

which is includes this PR but separates the "set cursor during expansion" and "templates" into two separate features. I used `%` for the default markers, to match fish (see https://fishshell.com/docs/current/cmds/abbr.html#add-subcommand).

It's released in [v5.4.0](https://github.com/olets/zsh-abbr/releases/tag/v5.4.0)

Docs:
- https://zsh-abbr.olets.dev/essential-commands.html#use-cursor-markers
- https://zsh-abbr.olets.dev/advanced.html

**Comment by olets** [comment]
@burneyy lmk if you'd like to be listed as a contributor in https://zsh-abbr.olets.dev/community/ and https://github.com/olets/zsh-abbr#community

**Comment by burneyy** [comment]
> @burneyy lmk if you'd like to be listed as a contributor in https://zsh-abbr.olets.dev/community/ and https://github.com/olets/zsh-abbr#community

Great that it has found its way into the release now, and yeah I would be happy to be listed among the contributors :)

**Comment by olets** [comment]
@all-contributors please add @burneyy for code. (#63)

**Pull request merged**
