### PR TITLE
Support inline expansion of Git abbreviations

### LINKED ISSUE #32: Multi-word / prefixed abbreviations
I don't really like using `import-git-aliases` as it produces too many conflicts with other commands. What I think would be really fantastic is if zsh-abbr could be clever enough to expand regular Git aliases contextually, i.e. when prefixed with the command `git`.

```
$ abbr add --git fp='fetch --prune'
$ git fp<space>
# expands inline to
$ git fetch --prune
```

What would it take to implement this? I see this in `_abbr_widget_expand`:

https://github.com/olets/zsh-abbr/blob/ccac4d044cec86fbb032ff9ea056eca246ea6041/zsh-abbr.zsh#L1236-L1242

I suppose we'd need another layer here, something like `_abbr_git_expansion`, which takes place only if `$words[0] == 'git'`. ~~I tried this, but even though `_abbr_git_expansion fp` prints `fetch --prune`, typing `git fp<space>` doesn't expand. What am I missing?~~ Zsh arrays are 1-indexed, haha.

### PR DESCRIPTION
**Pull request by henrebotha**
The existing Git alias functionality generates global abbreviations prefixed with "g". This is not ideal as it can clobber many other
commands or aliases.

This commit introduces functionality that allows for inline expansion of Git abbreviations, provided they are typed on a line that starts with the word "git".

It introduces a `--git` flag, analogous to the `--global` flag, that can be used to add a Git abbreviation.

Resolves #32.

### CODE REVIEW

**Comment by henrebotha** [comment]
This doesn't actually work correctly yet; it still expands when the command starts with something other than `git`. Working on it!

**Comment by olets** [comment]
Interesting. Before you sink too much time into it, can you explain the use case?

I'm excited to see what you do but heads up this week's really busy so I may be slow to respond.

**Comment by henrebotha** [comment]
No worries, whenever you have time.

The use case for me is: Just like I never want to type `git` when `g` will suffice, I want to be able to use my extensive suite of Git aliases instead of typing their full equivalents. Given a regular command alias `g=git`, typing `g<space>s<enter>` expands to `git status --short` and accepts it. Of course, I could simply have a command alias `gs`, which even accomplishes the same thing with one fewer keystroke; but then I run into the problem of colliding with other commands. (For example, I frequently have to make use of a command `gp` at work, which precludes having an alias such as `gp='git pull'`.) Having the ability to force an abbreviation to start with a particular prefix means I can "scope" all my Git aliases under a "namespace", and then go nuts with defining any Git aliases I want without having to worry about them potentially colliding with some command that just happens to start with "g".

---

It looks like it behaves now w.r.t. non-`git` commands. Still missing:

* [ ] The ability to `abbr expand` Git abbreviations.
* [ ] The ability to erase Git abbreviations.
* [ ] The ability to rename Git abbreviations.
* [ ] Updated Readme.

**Comment by olets** [comment]
(And sorry for the crossed wires, missed the issue you opened. Between that and my `ps` confusion I think my head must be too much in other places to think about this until the weekend 👍)

**Comment by olets** [comment]
Let's continue the broader convo over to #32 (no rush on a reply though)

**Comment by olets** [comment]
Closing in favor of possibly supporting multi-word command-position abbreviations, see 32 for discussion. Cool stuff tho!

**Pull request closed without merging**
