### PR TITLE
Add Fig as an installation method

### PR DESCRIPTION
**Pull request by brendanfalk**
We recently listed on `zsh-abbr` on [Fig Plugin Store](https://fig.io/plugins), so we'd love to have Fig displayed as a download method on your readme. Thanks so much and please let me know if you have any questions!

### CODE REVIEW

**Review by olets — APPROVED** [review]
Neat, thanks! I reworded your commit to follow the contribution guidelines, switched to a plain text link, and removed the target=_blank

**Comment by brendanfalk** [comment]
Exciting! Thanks so much @olets - I absolutely love zsh-abbr btw. Have been using it for a while now. So nifty

We should feature it in our plugin store!

**Comment by olets** [comment]
Glad you find it useful!

That'd be amazing. I'm putting what I _believe_ are the last touches on the next major version (v5), complete with new nicer-UX docs. Hoping to release it in the next week or two, that'd be a cool moment to feature it!

**Comment by olets** [comment]
Fig looks cool too, I'll check it out…

**Pull request merged**
